NODE_ENV: production
TASK_AUDIENCE: https://ancv-marketing-backend-er6fbprpra-as.a.run.app
AUTOMATION_SERVICE_ACCOUNTS: ancv-workflows@ancv-marketing-ai-agent.iam.gserviceaccount.com,ancv-automation@ancv-marketing-ai-agent.iam.gserviceaccount.com
WORDPRESS_BASE_URL: https://anninhcanhve.com
